### ISSUE TITLE
Silently fails if rofi is not available

### ISSUE THREAD

**Issue by xeruf** [ibizaman/pass-clip#4]
I have fzf installed and rofi not, but if I try to invoke `pass clip` then it fails silently.
Maybe this is already fixed in the commits since the latest release tough and you should simply make a new release ;)

**Comment by xeruf** [comment]
Indeed fixed, please do a release :)

**Comment by ibizaman** [comment]
Did you actually try the latest commits?

Regardless, releasing is a good idea :)

**Comment by ibizaman** [comment]
It is now released :)
